services:
  fpm:
    build:
      context: .
      dockerfile: docker/fpm.Dockerfile
    container_name: app
    restart: always
    depends_on:
      - mariadb
      - redis
    volumes:
        - app_data:/var/www/html
  nginx:
    build:
      context: docker
      dockerfile: nginx.Dockerfile
    container_name: nginx
    restart: always
    depends_on:
      - fpm
    ports:
        - "80:80"
    volumes:
        - app_data:/var/www/html
  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: filament
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
    volumes:
      - mariadb_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: admin
      UPLOAD_LIMIT: 4000M
    ports:
      - "82:80"
    depends_on:
      - mariadb
  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "83:8081"
    user: redis
    depends_on:
      - redis
  minio:
    image:  quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin
      - MINIO_DEFAULT_BUCKETS=filament
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
volumes:
  app_data:
  mariadb_data:
  redis_data:
  minio_data:
