name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image (fpm)
      run: docker build . --file docker/fpm.Dockerfile --tag filament-test-fpm:$(date +%s)
    - name: Build the Docker image (nginx)
      run: docker build . --file docker/nginx.Dockerfile --tag filament-test-nginx:$(date +%s)
